### ISSUE TITLE
ChannelTypeReliableUnordered test fails with timeout [windows]

### ISSUE THREAD

**Issue by ashellunts** [pion/datachannel#123]
Version: b9a54c547965a46b59720b9af4c8aa5b03b3ead5

```
$ go test -v
=== RUN   TestDataChannel
=== RUN   TestDataChannel/ChannelTypeReliableOrdered
=== RUN   TestDataChannel/ChannelTypeReliableUnordered
goroutine profile: total 9
2 @ 0x3fbb36 0x40b232 0x4f7251 0x429961
#       0x4f7250        github.com/pion/sctp.(*Association).writeLoop+0x230     C:/Users/shell/go/pkg/mod/github.com/pion/sctp@v1.7.12/association.go:559

2 @ 0x3fbb36 0x40b232 0x518865 0x4f67fe 0x429961
#       0x518864        github.com/pion/transport/test.(*bridgeConn).Read+0x124 C:/Users/shell/go/pkg/mod/github.com/pion/transport@v0.12.3/test/bridge.go:73
#       0x4f67fd        github.com/pion/sctp.(*Association).readLoop+0x15d      C:/Users/shell/go/pkg/mod/github.com/pion/sctp@v1.7.12/association.go:510

1 @ 0x3fbb36 0x3c686c 0x3c6298 0x496ab5 0x4986ce 0x495e62 0x49857f 0x4972dd 0x56124b 0x3fb797 0x429961
#       0x496ab4        testing.(*T).Run+0x374          C:/Program Files/Go/src/testing/testing.go:1307
#       0x4986cd        testing.runTests.func1+0x6d     C:/Program Files/Go/src/testing/testing.go:1598
#       0x495e61        testing.tRunner+0x101           C:/Program Files/Go/src/testing/testing.go:1259
#       0x49857e        testing.runTests+0x43e          C:/Program Files/Go/src/testing/testing.go:1596
#       0x4972dc        testing.(*M).Run+0x51c          C:/Program Files/Go/src/testing/testing.go:1504
#       0x56124a        main.main+0x14a                 _testmain.go:59
#       0x3fb796        runtime.main+0x216              C:/Program Files/Go/src/runtime/proc.go:255

1 @ 0x3fbb36 0x3c686c 0x3c6298 0x496ab5 0x55c4a5 0x495e62 0x429961
#       0x496ab4        testing.(*T).Run+0x374                                  C:/Program Files/Go/src/testing/testing.go:1307
#       0x55c4a4        github.com/pion/datachannel.TestDataChannel+0x164       D:/git/pion/datachannel/datachannel_test.go:347
#       0x495e61        testing.tRunner+0x101                                   C:/Program Files/Go/src/testing/testing.go:1259

1 @ 0x3fbb36 0x3c686c 0x3c62d8 0x558b17 0x558afe 0x55c850 0x495e62 0x429961
#       0x558b16        github.com/pion/sctp.(*Association).AcceptStream+0x36   C:/Users/shell/go/pkg/mod/github.com/pion/sctp@v1.7.12/association.go:1315
#       0x558afd        github.com/pion/datachannel.Accept+0x1d                 D:/git/pion/datachannel/datachannel.go:116
#       0x55c84f        github.com/pion/datachannel.TestDataChannel.func2+0x2ef D:/git/pion/datachannel/datachannel_test.go:373
#       0x495e61        testing.tRunner+0x101                                   C:/Program Files/Go/src/testing/testing.go:1259

1 @ 0x3fbb36 0x40b232 0x511bb1 0x429961
#       0x511bb0        github.com/pion/sctp.(*rtxTimer).start.func1+0xd0       C:/Users/shell/go/pkg/mod/github.com/pion/sctp@v1.7.12/rtx_timer.go:151

1 @ 0x423425 0x4c3875 0x4c368d 0x4c082b 0x51ac65 0x429961
#       0x423424        runtime/pprof.runtime_goroutineProfileWithLabels+0x24   C:/Program Files/Go/src/runtime/mprof.go:746
#       0x4c3874        runtime/pprof.writeRuntimeProfile+0xb4                  C:/Program Files/Go/src/runtime/pprof/pprof.go:724
#       0x4c368c        runtime/pprof.writeGoroutine+0x4c                       C:/Program Files/Go/src/runtime/pprof/pprof.go:684
#       0x4c082a        runtime/pprof.(*Profile).WriteTo+0x14a                  C:/Program Files/Go/src/runtime/pprof/pprof.go:331
#       0x51ac64        github.com/pion/transport/test.TimeOut.func1+0x44       C:/Users/shell/go/pkg/mod/github.com/pion/transport@v0.12.3/test/util.go:21

panic: timeout

goroutine 55 [running]:
github.com/pion/transport/test.TimeOut.func1()
        C:/Users/shell/go/pkg/mod/github.com/pion/transport@v0.12.3/test/util.go:24 +0xa5
created by time.goFunc
        C:/Program Files/Go/src/time/sleep.go:180 +0x31
exit status 2
FAIL    github.com/pion/datachannel     10.495s
```

**Comment by Sean-Der** [comment]
I haven't been able to reproduce this. If anyone still is seeing this please re-open!
